Repository dataware-tools/protocols, pull requests merged in 2021-12, with the labels that each got.

#52 Add `database_id` and `record_id` to JobPostModel
  schemas/apis/api-job-store/schema.v1.yaml
Labels: size/S, approved

#51 Add endpoint for batch updating user roles
  schemas/apis/api-permission-manager/schema.v1.yaml
Labels: do-not-merge/hold, size/M, approved, lgtm

#53 Add parameter `database_id` to api-job-store
  schemas/apis/api-job-store/schema.v1.yaml
Labels: size/M, approved, lgtm
